{
 "title": "Basic Composition",
 "panels": [
  {
   "title": "Python Average Latency (milliseconds)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Google",
     "measurement": "avg_latency_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "google" },
      { "condition": "AND", "key": "runtime", "operator": "=", "value": "python" }
     ]
    },
    {
     "alias": "Amazon",
     "measurement": "avg_latency_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "amazon" },
      { "condition": "AND", "key": "runtime", "operator": "=", "value": "python" }
     ]
    },
    {
     "alias": "OpenWhisk",
     "measurement": "avg_latency_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "openwhisk" },
      { "condition": "AND", "key": "runtime", "operator": "=", "value": "python" }
     ]
    }
   ]
  },
  {
   "title": "Python Cold Start Latency (milliseconds)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Google",
     "measurement": "cold_start_latency_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "runtime", "operator": "=", "value": "python" },
      { "condition": "AND", "key": "provider", "operator": "=", "value": "google" }
     ]
    },
    {
     "alias": "Amazon",
     "measurement": "cold_start_latency_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "runtime", "operator": "=", "value": "python" },
      { "condition": "AND", "key": "provider", "operator": "=", "value": "amazon" }
     ]
    },
    {
     "alias": "OpenWhisk",
     "measurement": "cold_start_latency_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "runtime", "operator": "=", "value": "python" },
      { "condition": "AND", "key": "provider", "operator": "=", "value": "openwhisk" }
     ]
    }
   ]
  },
  {
   "title": "Java Average Latency (milliseconds)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Google",
     "measurement": "avg_latency_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "runtime", "operator": "=", "value": "java" },
      { "condition": "AND", "key": "provider", "operator": "=", "value": "google" }
     ]
    },
    {
     "alias": "Amazon",
     "measurement": "avg_latency_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "runtime", "operator": "=", "value": "java" },
      { "condition": "AND", "key": "provider", "operator": "=", "value": "amazon" }
     ]
    },
    {
     "alias": "OpenWhisk",
     "measurement": "avg_latency_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "runtime", "operator": "=", "value": "java" },
      { "condition": "AND", "key": "provider", "operator": "=", "value": "openwhisk" }
     ]
    }
   ]
  },
  {
   "title": "Java Cold Start Latency (milliseconds)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Google",
     "measurement": "cold_start_latency_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "runtime", "operator": "=", "value": "java" },
      { "condition": "AND", "key": "provider", "operator": "=", "value": "google" }
     ]
    },
    {
     "alias": "Amazon",
     "measurement": "cold_start_latency_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "runtime", "operator": "=", "value": "java" },
      { "condition": "AND", "key": "provider", "operator": "=", "value": "amazon" }
     ]
    },
    {
     "alias": "OpenWhisk",
     "measurement": "cold_start_latency_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "runtime", "operator": "=", "value": "java" },
      { "condition": "AND", "key": "provider", "operator": "=", "value": "openwhisk" }
     ]
    }
   ]
  },
  {
   "title": "Node Average Latency (milliseconds)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Google",
     "measurement": "avg_latency_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "runtime", "operator": "=", "value": "node" },
      { "condition": "AND", "key": "provider", "operator": "=", "value": "google" }
     ]
    },
    {
     "alias": "Amazon",
     "measurement": "avg_latency_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "runtime", "operator": "=", "value": "node" },
      { "condition": "AND", "key": "provider", "operator": "=", "value": "amazon" }
     ]
    },
    {
     "alias": "OpenWhisk",
     "measurement": "avg_latency_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "runtime", "operator": "=", "value": "node" },
      { "condition": "AND", "key": "provider", "operator": "=", "value": "openwhisk" }
     ]
    }
   ]
  },
  {
   "title": "Node Cold Start Latency (milliseconds)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Google",
     "measurement": "cold_start_latency_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "runtime", "operator": "=", "value": "node" },
      { "condition": "AND", "key": "provider", "operator": "=", "value": "google" }
     ]
    },
    {
     "alias": "Amazon",
     "measurement": "cold_start_latency_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "runtime", "operator": "=", "value": "node" },
      { "condition": "AND", "key": "provider", "operator": "=", "value": "amazon" }
     ]
    },
    {
     "alias": "OpenWhisk",
     "measurement": "cold_start_latency_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "runtime", "operator": "=", "value": "node" },
      { "condition": "AND", "key": "provider", "operator": "=", "value": "openwhisk" }
     ]
    }
   ]
  },
  {
   "title": "Python Requests Throughput (requests per second)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Google",
     "measurement": "requests_throughput_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "runtime", "operator": "=", "value": "python" },
      { "condition": "AND", "key": "provider", "operator": "=", "value": "google" }
     ]
    },
    {
     "alias": "Amazon",
     "measurement": "requests_throughput_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "runtime", "operator": "=", "value": "python" },
      { "condition": "AND", "key": "provider", "operator": "=", "value": "amazon" }
     ]
    },
    {
     "alias": "OpenWhisk",
     "measurement": "requests_throughput_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "runtime", "operator": "=", "value": "python" },
      { "condition": "AND", "key": "provider", "operator": "=", "value": "openwhisk" }
     ]
    }
   ]
  },
  {
   "title": "Python Transfer Throughput (kilobytes per second)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Google",
     "measurement": "transfer_throughput_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "runtime", "operator": "=", "value": "python" },
      { "condition": "AND", "key": "provider", "operator": "=", "value": "google" }
     ]
    },
    {
     "alias": "Amazon",
     "measurement": "transfer_throughput_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "runtime", "operator": "=", "value": "python" },
      { "condition": "AND", "key": "provider", "operator": "=", "value": "amazon" }
     ]
    },
    {
     "alias": "OpenWhisk",
     "measurement": "transfer_throughput_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "runtime", "operator": "=", "value": "python" },
      { "condition": "AND", "key": "provider", "operator": "=", "value": "openwhisk" }
     ]
    }
   ]
  },
  {
   "title": "Java Requests Throughput (requests per second)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Google",
     "measurement": "requests_throughput_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "runtime", "operator": "=", "value": "java" },
      { "condition": "AND", "key": "provider", "operator": "=", "value": "google" }
     ]
    },
    {
     "alias": "Amazon",
     "measurement": "requests_throughput_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "runtime", "operator": "=", "value": "java" },
      { "condition": "AND", "key": "provider", "operator": "=", "value": "amazon" }
     ]
    },
    {
     "alias": "OpenWhisk",
     "measurement": "requests_throughput_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "runtime", "operator": "=", "value": "java" },
      { "condition": "AND", "key": "provider", "operator": "=", "value": "openwhisk" }
     ]
    }
   ]
  },
  {
   "title": "Java Transfer Throughput (kilobytes per second)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Google",
     "measurement": "transfer_throughput_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "runtime", "operator": "=", "value": "java" },
      { "condition": "AND", "key": "provider", "operator": "=", "value": "google" }
     ]
    },
    {
     "alias": "Amazon",
     "measurement": "transfer_throughput_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "runtime", "operator": "=", "value": "java" },
      { "condition": "AND", "key": "provider", "operator": "=", "value": "amazon" }
     ]
    },
    {
     "alias": "OpenWhisk",
     "measurement": "transfer_throughput_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "runtime", "operator": "=", "value": "java" },
      { "condition": "AND", "key": "provider", "operator": "=", "value": "openwhisk" }
     ]
    }
   ]
  },
  {
   "title": "Node Requests Throughput (requests per second)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Google",
     "measurement": "requests_throughput_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "runtime", "operator": "=", "value": "node" },
      { "condition": "AND", "key": "provider", "operator": "=", "value": "google" }
     ]
    },
    {
     "alias": "Amazon",
     "measurement": "requests_throughput_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "runtime", "operator": "=", "value": "node" },
      { "condition": "AND", "key": "provider", "operator": "=", "value": "amazon" }
     ]
    },
    {
     "alias": "OpenWhisk",
     "measurement": "requests_throughput_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "runtime", "operator": "=", "value": "node" },
      { "condition": "AND", "key": "provider", "operator": "=", "value": "openwhisk" }
     ]
    }
   ]
  },
  {
   "title": "Node Transfer Throughput (kilobytes per second)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Google",
     "measurement": "transfer_throughput_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "runtime", "operator": "=", "value": "node" },
      { "condition": "AND", "key": "provider", "operator": "=", "value": "google" }
     ]
    },
    {
     "alias": "Amazon",
     "measurement": "transfer_throughput_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "runtime", "operator": "=", "value": "node" },
      { "condition": "AND", "key": "provider", "operator": "=", "value": "amazon" }
     ]
    },
    {
     "alias": "OpenWhisk",
     "measurement": "transfer_throughput_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "runtime", "operator": "=", "value": "node" },
      { "condition": "AND", "key": "provider", "operator": "=", "value": "openwhisk" }
     ]
    }
   ]
  },
  {
   "title": "Global Latency Stats",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "alias": "Python Google Latency",
     "measurement": "avg_latency_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "google" },
      { "condition": "AND", "key": "runtime", "operator": "=", "value": "python" }
     ]
    },
    {
     "alias": "Python Amazon Latency",
     "measurement": "avg_latency_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "amazon" },
      { "condition": "AND", "key": "runtime", "operator": "=", "value": "python" }
     ]
    },
    {
     "alias": "Python OpenWhisk Latency",
     "measurement": "avg_latency_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "openwhisk" },
      { "condition": "AND", "key": "runtime", "operator": "=", "value": "python" }
     ]
    },
    {
     "alias": "Java Google Latency",
     "measurement": "avg_latency_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "google" },
      { "condition": "AND", "key": "runtime", "operator": "=", "value": "java" }
     ]
    },
    {
     "alias": "Java Amazon Latency",
     "measurement": "avg_latency_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "amazon" },
      { "condition": "AND", "key": "runtime", "operator": "=", "value": "java" }
     ]
    },
    {
     "alias": "Java OpenWhisk Latency",
     "measurement": "avg_latency_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "openwhisk" },
      { "condition": "AND", "key": "runtime", "operator": "=", "value": "java" }
     ]
    },
    {
     "alias": "Node.js Google Latency",
     "measurement": "avg_latency_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "google" },
      { "condition": "AND", "key": "runtime", "operator": "=", "value": "node" }
     ]
    },
    {
     "alias": "Node.js Amazon Latency",
     "measurement": "avg_latency_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "amazon" },
      { "condition": "AND", "key": "runtime", "operator": "=", "value": "node" }
     ]
    },
    {
     "alias": "Node.js OpenWhisk Latency",
     "measurement": "avg_latency_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "openwhisk" },
      { "condition": "AND", "key": "runtime", "operator": "=", "value": "node" }
     ]
    },
    {
     "alias": "Python Google Cold Start Latency",
     "measurement": "cold_start_latency_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "google" },
      { "condition": "AND", "key": "runtime", "operator": "=", "value": "python" }
     ]
    },
    {
     "alias": "Python Amazon Cold Start Latency",
     "measurement": "cold_start_latency_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "amazon" },
      { "condition": "AND", "key": "runtime", "operator": "=", "value": "python" }
     ]
    },
    {
     "alias": "Python OpenWhisk Cold Start Latency",
     "measurement": "cold_start_latency_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "openwhisk" },
      { "condition": "AND", "key": "runtime", "operator": "=", "value": "python" }
     ]
    },
    {
     "alias": "Java Google Cold Start Latency",
     "measurement": "cold_start_latency_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "google" },
      { "condition": "AND", "key": "runtime", "operator": "=", "value": "java" }
     ]
    },
    {
     "alias": "Java Amazon Cold Start Latency",
     "measurement": "cold_start_latency_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "amazon" },
      { "condition": "AND", "key": "runtime", "operator": "=", "value": "java" }
     ]
    },
    {
     "alias": "Java OpenWhisk Cold Start Latency",
     "measurement": "cold_start_latency_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "openwhisk" },
      { "condition": "AND", "key": "runtime", "operator": "=", "value": "java" }
     ]
    },
    {
     "alias": "Node.js Google Cold Start Latency",
     "measurement": "cold_start_latency_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "google" },
      { "condition": "AND", "key": "runtime", "operator": "=", "value": "node" }
     ]
    },
    {
     "alias": "Node.js Amazon Cold Start Latency",
     "measurement": "cold_start_latency_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "amazon" },
      { "condition": "AND", "key": "runtime", "operator": "=", "value": "node" }
     ]
    },
    {
     "alias": "Node.js OpenWhisk Cold Start Latency",
     "measurement": "cold_start_latency_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "openwhisk" },
      { "condition": "AND", "key": "runtime", "operator": "=", "value": "node" }
     ]
    }
   ]
  },
  {
   "title": "Global Throughput Stats",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "alias": "Python Google Request Throughput (request per second)",
     "measurement": "requests_throughput_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "google" },
      { "condition": "AND", "key": "runtime", "operator": "=", "value": "python" }
     ]
    },
    {
     "alias": "Python Amazon Request Throughput (request per second)",
     "measurement": "requests_throughput_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "amazon" },
      { "condition": "AND", "key": "runtime", "operator": "=", "value": "python" }
     ]
    },
    {
     "alias": "Python OpenWhisk Request Throughput (request per second)",
     "measurement": "requests_throughput_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "openwhisk" },
      { "condition": "AND", "key": "runtime", "operator": "=", "value": "python" }
     ]
    },
    {
     "alias": "Java Google Request Throughput (request per second)",
     "measurement": "requests_throughput_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "google" },
      { "condition": "AND", "key": "runtime", "operator": "=", "value": "java" }
     ]
    },
    {
     "alias": "Java Amazon Request Throughput (request per second)",
     "measurement": "requests_throughput_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "amazon" },
      { "condition": "AND", "key": "runtime", "operator": "=", "value": "java" }
     ]
    },
    {
     "alias": "Java OpenWhisk Request Throughput (request per second)",
     "measurement": "requests_throughput_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "openwhisk" },
      { "condition": "AND", "key": "runtime", "operator": "=", "value": "java" }
     ]
    },
    {
     "alias": "Node.js Google Request Throughput (request per second)",
     "measurement": "requests_throughput_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "google" },
      { "condition": "AND", "key": "runtime", "operator": "=", "value": "node" }
     ]
    },
    {
     "alias": "Node.js Amazon Request Throughput (request per second)",
     "measurement": "requests_throughput_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "amazon" },
      { "condition": "AND", "key": "runtime", "operator": "=", "value": "node" }
     ]
    },
    {
     "alias": "Node.js OpenWhisk Request Throughput (request per second)",
     "measurement": "requests_throughput_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "openwhisk" },
      { "condition": "AND", "key": "runtime", "operator": "=", "value": "node" }
     ]
    },
    {
     "alias": "Python Google Transfer Throughput (kilobyte per second)",
     "measurement": "transfer_throughput_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "google" },
      { "condition": "AND", "key": "runtime", "operator": "=", "value": "python" }
     ]
    },
    {
     "alias": "Python Amazon Transfer Throughput (kilobyte per second)",
     "measurement": "transfer_throughput_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "amazon" },
      { "condition": "AND", "key": "runtime", "operator": "=", "value": "python" }
     ]
    },
    {
     "alias": "Python OpenWhisk Transfer Throughput (kilobyte per second)",
     "measurement": "transfer_throughput_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "openwhisk" },
      { "condition": "AND", "key": "runtime", "operator": "=", "value": "python" }
     ]
    },
    {
     "alias": "Java Google Transfer Throughput (kilobyte per second)",
     "measurement": "transfer_throughput_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "google" },
      { "condition": "AND", "key": "runtime", "operator": "=", "value": "java" }
     ]
    },
    {
     "alias": "Java Amazon Transfer Throughput (kilobyte per second)",
     "measurement": "transfer_throughput_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "amazon" },
      { "condition": "AND", "key": "runtime", "operator": "=", "value": "java" }
     ]
    },
    {
     "alias": "Java OpenWhisk Transfer Throughput (kilobyte per second)",
     "measurement": "transfer_throughput_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "openwhisk" },
      { "condition": "AND", "key": "runtime", "operator": "=", "value": "java" }
     ]
    },
    {
     "alias": "Node.js Google Transfer Throughput (kilobyte per second)",
     "measurement": "transfer_throughput_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "google" },
      { "condition": "AND", "key": "runtime", "operator": "=", "value": "node" }
     ]
    },
    {
     "alias": "Node.js Amazon Transfer Throughput (kilobyte per second)",
     "measurement": "transfer_throughput_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "amazon" },
      { "condition": "AND", "key": "runtime", "operator": "=", "value": "node" }
     ]
    },
    {
     "alias": "Node.js OpenWhisk Transfer Throughput (kilobyte per second)",
     "measurement": "transfer_throughput_basic-composition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "openwhisk" },
      { "condition": "AND", "key": "runtime", "operator": "=", "value": "node" }
     ]
    }
   ]
  }
 ]
}