{
 "title": "Cycle Translator",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Python Average Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Google",
     "measurement": "avg_latency_cycle-translator",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "google" },
      { "condition": "AND", "key": "runtime", "operator": "=", "value": "python" }
     ]
    },
    {
     "alias": "Amazon",
     "measurement": "avg_latency_cycle-translator",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "amazon" },
      { "condition": "AND", "key": "runtime", "operator": "=", "value": "python" }
     ]
    },
    {
     "alias": "Open Whisk",
     "measurement": "avg_latency_cycle-translator",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "openwhisk" },
      { "condition": "AND", "key": "runtime", "operator": "=", "value": "python" }
     ]
    }
   ]
  },
  {
   "title": "Python Cold Start Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Google",
     "measurement": "cold_start_latency_cycle-translator",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "runtime", "operator": "=", "value": "python" },
      { "condition": "AND", "key": "provider", "operator": "=", "value": "google" }
     ]
    },
    {
     "alias": "Amazon",
     "measurement": "cold_start_latency_cycle-translator",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "runtime", "operator": "=", "value": "python" },
      { "condition": "AND", "key": "provider", "operator": "=", "value": "amazon" }
     ]
    },
    {
     "alias": "Open Whisk",
     "measurement": "cold_start_latency_cycle-translator",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "runtime", "operator": "=", "value": "python" },
      { "condition": "AND", "key": "provider", "operator": "=", "value": "openwhisk" }
     ]
    }
   ]
  },
  {
   "title": "Java Average Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Google",
     "measurement": "avg_latency_cycle-translator",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "runtime", "operator": "=", "value": "java" },
      { "condition": "AND", "key": "provider", "operator": "=", "value": "google" }
     ]
    },
    {
     "alias": "Amazon",
     "measurement": "avg_latency_cycle-translator",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "runtime", "operator": "=", "value": "java" },
      { "condition": "AND", "key": "provider", "operator": "=", "value": "amazon" }
     ]
    },
    {
     "alias": "Open Whisk",
     "measurement": "avg_latency_cycle-translator",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "runtime", "operator": "=", "value": "java" },
      { "condition": "AND", "key": "provider", "operator": "=", "value": "openwhisk" }
     ]
    }
   ]
  },
  {
   "title": "Java Cold Start Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Google",
     "measurement": "cold_start_latency_cycle-translator",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "runtime", "operator": "=", "value": "java" },
      { "condition": "AND", "key": "provider", "operator": "=", "value": "google" }
     ]
    },
    {
     "alias": "Amazon",
     "measurement": "cold_start_latency_cycle-translator",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "runtime", "operator": "=", "value": "java" },
      { "condition": "AND", "key": "provider", "operator": "=", "value": "amazon" }
     ]
    },
    {
     "alias": "Open Whisk",
     "measurement": "cold_start_latency_cycle-translator",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "runtime", "operator": "=", "value": "java" },
      { "condition": "AND", "key": "provider", "operator": "=", "value": "openwhisk" }
     ]
    }
   ]
  },
  {
   "title": "Node Average Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Google",
     "measurement": "avg_latency_cycle-translator",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "runtime", "operator": "=", "value": "node" },
      { "condition": "AND", "key": "provider", "operator": "=", "value": "google" }
     ]
    },
    {
     "alias": "Amazon",
     "measurement": "avg_latency_cycle-translator",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "runtime", "operator": "=", "value": "node" },
      { "condition": "AND", "key": "provider", "operator": "=", "value": "amazon" }
     ]
    },
    {
     "alias": "Open Whisk",
     "measurement": "avg_latency_cycle-translator",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "runtime", "operator": "=", "value": "node" },
      { "condition": "AND", "key": "provider", "operator": "=", "value": "openwhisk" }
     ]
    }
   ]
  },
  {
   "title": "Node Cold Start Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Google",
     "measurement": "cold_start_latency_cycle-translator",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "runtime", "operator": "=", "value": "node" },
      { "condition": "AND", "key": "provider", "operator": "=", "value": "google" }
     ]
    },
    {
     "alias": "Amazon",
     "measurement": "cold_start_latency_cycle-translator",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "runtime", "operator": "=", "value": "node" },
      { "condition": "AND", "key": "provider", "operator": "=", "value": "amazon" }
     ]
    },
    {
     "alias": "Open Whisk",
     "measurement": "cold_start_latency_cycle-translator",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "runtime", "operator": "=", "value": "node" },
      { "condition": "AND", "key": "provider", "operator": "=", "value": "openwhisk" }
     ]
    }
   ]
  },
  {
   "title": "Python Requests Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Google",
     "measurement": "requests_throughput_cycle-translator",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "runtime", "operator": "=", "value": "python" },
      { "condition": "AND", "key": "provider", "operator": "=", "value": "google" }
     ]
    },
    {
     "alias": "Amazon",
     "measurement": "requests_throughput_cycle-translator",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "runtime", "operator": "=", "value": "python" },
      { "condition": "AND", "key": "provider", "operator": "=", "value": "amazon" }
     ]
    },
    {
     "alias": "Open Whisk",
     "measurement": "requests_throughput_cycle-translator",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "runtime", "operator": "=", "value": "python" },
      { "condition": "AND", "key": "provider", "operator": "=", "value": "openwhisk" }
     ]
    }
   ]
  },
  {
   "title": "Python Transfer Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Google",
     "measurement": "transfer_throughput_cycle-translator",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "runtime", "operator": "=", "value": "python" },
      { "condition": "AND", "key": "provider", "operator": "=", "value": "google" }
     ]
    },
    {
     "alias": "Amazon",
     "measurement": "transfer_throughput_cycle-translator",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "runtime", "operator": "=", "value": "python" },
      { "condition": "AND", "key": "provider", "operator": "=", "value": "amazon" }
     ]
    },
    {
     "alias": "Open Whisk",
     "measurement": "transfer_throughput_cycle-translator",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "runtime", "operator": "=", "value": "python" },
      { "condition": "AND", "key": "provider", "operator": "=", "value": "openwhisk" }
     ]
    }
   ]
  },
  {
   "title": "Java Requests Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Google",
     "measurement": "requests_throughput_cycle-translator",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "runtime", "operator": "=", "value": "java" },
      { "condition": "AND", "key": "provider", "operator": "=", "value": "google" }
     ]
    },
    {
     "alias": "Amazon",
     "measurement": "requests_throughput_cycle-translator",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "runtime", "operator": "=", "value": "java" },
      { "condition": "AND", "key": "provider", "operator": "=", "value": "amazon" }
     ]
    },
    {
     "alias": "Open Whisk",
     "measurement": "requests_throughput_cycle-translator",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "runtime", "operator": "=", "value": "java" },
      { "condition": "AND", "key": "provider", "operator": "=", "value": "openwhisk" }
     ]
    }
   ]
  },
  {
   "title": "Java Transfer Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Google",
     "measurement": "transfer_throughput_cycle-translator",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "runtime", "operator": "=", "value": "java" },
      { "condition": "AND", "key": "provider", "operator": "=", "value": "google" }
     ]
    },
    {
     "alias": "Amazon",
     "measurement": "transfer_throughput_cycle-translator",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "runtime", "operator": "=", "value": "java" },
      { "condition": "AND", "key": "provider", "operator": "=", "value": "amazon" }
     ]
    },
    {
     "alias": "Open Whisk",
     "measurement": "transfer_throughput_cycle-translator",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "runtime", "operator": "=", "value": "java" },
      { "condition": "AND", "key": "provider", "operator": "=", "value": "openwhisk" }
     ]
    }
   ]
  },
  {
   "title": "Node Requests Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Google",
     "measurement": "requests_throughput_cycle-translator",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "runtime", "operator": "=", "value": "node" },
      { "condition": "AND", "key": "provider", "operator": "=", "value": "google" }
     ]
    },
    {
     "alias": "Amazon",
     "measurement": "requests_throughput_cycle-translator",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "runtime", "operator": "=", "value": "node" },
      { "condition": "AND", "key": "provider", "operator": "=", "value": "amazon" }
     ]
    },
    {
     "alias": "Open Whisk",
     "measurement": "requests_throughput_cycle-translator",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "runtime", "operator": "=", "value": "node" },
      { "condition": "AND", "key": "provider", "operator": "=", "value": "openwhisk" }
     ]
    }
   ]
  },
  {
   "title": "Node Transfer Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Google",
     "measurement": "transfer_throughput_cycle-translator",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "runtime", "operator": "=", "value": "node" },
      { "condition": "AND", "key": "provider", "operator": "=", "value": "google" }
     ]
    },
    {
     "alias": "Amazon",
     "measurement": "transfer_throughput_cycle-translator",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "runtime", "operator": "=", "value": "node" },
      { "condition": "AND", "key": "provider", "operator": "=", "value": "amazon" }
     ]
    },
    {
     "alias": "Open Whisk",
     "measurement": "transfer_throughput_cycle-translator",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "runtime", "operator": "=", "value": "node" },
      { "condition": "AND", "key": "provider", "operator": "=", "value": "openwhisk" }
     ]
    }
   ]
  }
 ]
}